steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f",
        "apps/blog/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/kylepericakdotcom:$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/kylepericakdotcom:latest",
        ".",
      ]

  - name: gcr.io/$PROJECT_ID/kylepericakdotcom:$COMMIT_SHA
    entrypoint: bash
    args: ["bin/build-blog-files.sh", "/workspace/out"]
    dir: "/app"

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "/workspace/out", "gs://kyle.pericak.com"]

images:
  - gcr.io/$PROJECT_ID/kylepericakdotcom:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/kylepericakdotcom:latest
