steps:

  - name: gcr.io/kylepericak/kylepericakdotcom
    entrypoint: bash
    args: ["bin/build-blog-files.sh", "/workspace/out"]
    dir: "/app"

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "/workspace/out", "gs://kyle.pericak.com"]
