# kytrade app helmfile

environments:

  # default env is for testing on generic clusters, like cheaper saas k8s options
  default:
  # staging is my home cluster
  staging:
  # production is AWS EKS
  production:


repositories:
 - name: bitnami
   url: https://charts.bitnami.com/bitnami


releases:
  - name: kytrade-client
    chart: ./kytrade-client
    namespace: kytrade

  - name: kytrade-api
    chart: ./kytrade-api
    namespace: kytreade
