repositories:
 - name: bitnami
   url: https://charts.bitnami.com/bitnami

releases:
- name: postgres
  namespace: kytrade
  chart: bitnami/postgresql
  set:
  - name: global.postgresql.auth.username
    value: POSTGRES_USER
  - name: global.postgresql.auth.password
    value: POSTGRES_PASSWORD
  - name: global.postgresql.auth.database
    value: kytrade
