#!/usr/bin/env python3
"""Build the Multi-Megastructures mod.

Reads vanilla Stellaris megastructure files from the local Steam install and
generates overrides that strip the per-empire and per-system build limits.

Approach: instead of brace-aware block removal, we redirect every limit-tracking
reference to an inert sentinel flag that we never set anywhere.

- `has_country_flag = built_<name>`        -> `has_country_flag = mmegs_unused_flag`
- `set_country_flag = built_<name>`        -> `set_country_flag = mmegs_unused_flag`
- `remove_country_flag = built_<name>`     -> `remove_country_flag = mmegs_unused_flag`
- `has_no_non_gate_megastructure = yes`    -> `always = yes`

Because `mmegs_unused_flag` is never set:
- `NOT = { has_country_flag = built_X }`     (gate "haven't built one") is always true -> gate passes
- `NOR = { has_country_flag = built_X, ... }` (gate "none built") is always true -> gate passes
- `has_country_flag = built_X` in `limit = { ... }` (effect tracking) is always false -> effect skipped
- `set_country_flag = built_X` becomes a no-op that sets the sentinel

Structural integrity is preserved (no empty blocks introduced), and per-game-patch
updates only require re-running this script against the updated vanilla files.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
MOD_DIR = SCRIPT_DIR.parent / "mod"
OUTPUT_DIR = MOD_DIR / "common" / "megastructures"

VANILLA_DIR = (
    Path.home()
    / "Library"
    / "Application Support"
    / "Steam"
    / "steamapps"
    / "common"
    / "Stellaris"
    / "common"
    / "megastructures"
)

# Files where the per-empire / per-system limit lives.
# Determined by grepping vanilla for `has_no_non_gate_megastructure` and
# `has_country_flag = built_`.
TARGET_FILES = [
    "00_ring_world.txt",
    "01_dyson_sphere.txt",
    "02_spy_orb.txt",
    "03_think_tank.txt",
    "06_matter_decompressor.txt",
    "07_strategic_coordination_center.txt",
    "08_mega_art_installation.txt",
    "09_interstellar_assembly.txt",
    "11_mega_shipyard.txt",
    "13_quantum_catapult.txt",
    "16_cosmogenesis_world.txt",
    "18_dyson_swarm.txt",
    "21_behemoth_egg.txt",
    "22_galactic_crucible.txt",
]

SENTINEL_FLAG = "mmegs_unused_flag"

REPLACEMENTS = [
    (
        re.compile(r"(has_country_flag\s*=\s*)built_[A-Za-z0-9_]+"),
        rf"\1{SENTINEL_FLAG}",
    ),
    (
        re.compile(r"(set_country_flag\s*=\s*)built_[A-Za-z0-9_]+"),
        rf"\1{SENTINEL_FLAG}",
    ),
    (
        re.compile(r"(remove_country_flag\s*=\s*)built_[A-Za-z0-9_]+"),
        rf"\1{SENTINEL_FLAG}",
    ),
    (
        re.compile(r"has_no_non_gate_megastructure\s*=\s*yes"),
        "always = yes",
    ),
]

# Counters for the per-empire build cap that the AI/UI reads against megastructure
# count modifiers. Adding a large boost ensures the cap never bites.
# We append this near the top of each generated file as a country_modifier-free
# header comment; the actual cap lift comes from removing the gates above.

HEADER_TEMPLATE = (
    "# Generated by apps/mods/stellaris/multi-megastructures/scripts/build.py\n"
    "# Source: vanilla Stellaris (Cetus v4.3.*).\n"
    "# Modifications:\n"
    f"#   - all `built_<megastructure>` country flags rewritten to `{SENTINEL_FLAG}`\n"
    "#     (a flag never set anywhere), which makes per-empire `NOT/NOR` gates\n"
    "#     always pass and per-empire flag-set effects no-op.\n"
    "#   - `has_no_non_gate_megastructure = yes` (per-system uniqueness gate)\n"
    "#     rewritten to `always = yes`.\n"
    "\n"
)


def transform(text: str) -> tuple[str, int]:
    """Apply all replacements; return (new_text, replacement_count)."""
    total = 0
    for pattern, replacement in REPLACEMENTS:
        text, n = pattern.subn(replacement, text)
        total += n
    return text, total


def main() -> int:
    if not VANILLA_DIR.exists():
        print(
            f"ERROR: vanilla megastructure dir not found: {VANILLA_DIR}",
            file=sys.stderr,
        )
        print(
            "Install Stellaris via Steam, or edit VANILLA_DIR in this script.",
            file=sys.stderr,
        )
        return 1

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for name in TARGET_FILES:
        src = VANILLA_DIR / name
        if not src.exists():
            print(f"WARN: vanilla file missing: {src}", file=sys.stderr)
            continue
        original = src.read_text(encoding="utf-8")
        transformed, count = transform(original)
        dest = OUTPUT_DIR / name
        dest.write_text(HEADER_TEMPLATE + transformed, encoding="utf-8")
        print(f"  {name}: {count} replacements")

    print(f"\nWrote {len(TARGET_FILES)} files to {OUTPUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
