# values.yaml

# charts/values.yaml at master · bitnami/charts
# https://github.com/bitnami/charts/blob/master/bitnami/metallb/values.yaml

## To configure MetalLB, you must specify ONE of the following two
## options.
#
## existingConfigMap specifies the name of an externally-defined
## ConfigMap to use as the configuration. Helm will not manage the
## contents of this ConfigMap, it is your responsibility to create it.
#
# existingConfigMap: metallb-config
#
## configInline specifies MetalLB's configuration directly, in yaml
## format. When configInline is used, Helm manages MetalLB's
## configuration ConfigMap as part of the release, and
## existingConfigMap is ignored.
## Refer to https://metallb.universe.tf/configuration/ for
## available options.
#
configInline: |
    # https://metallb.universe.tf/configuration/#layer-2-configuration
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      # Replace with idle IP in the same subnet as the node IP.
      - 192.168.2.230-192.168.2.249
      # - {{ .Values.addresses }}
