{{- if .Values.paiResponder.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pai-responder.fullname" . }}-state
  labels:
    {{- include "pai-responder.labels" . | nindent 4 }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- end }}
