apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: blog-staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.registry.storageClass }}
  resources:
    requests:
      storage: {{ .Values.registry.storage }}
